### ISSUE TITLE
Is it possible to also merge and use physics assets of the merged parts?

### ISSUE THREAD

**Issue by Hextionsh0t** [Luis24989/SkeletalMeshMerger#1]
Hey just wanted to ask if it's possible, could be a nice feature :)

**Comment by Luis24989** [comment]
Hey,

As far as I noticed by now you can create physic assets for the mesh parts and assign them in their meshes. 
After merging the meshes ragdoll worked fine for me.
The only problem I noticed so far is that cloth simulation stops working after merging together the meshes. 
I hope that answers your question.
Kind regards

Luis

**Comment by Hextionsh0t** [comment]
I'm making a game with robots and their parts have different pieces, i
would love them to have accurate collision thats why i cant use premade
physics assets, too many variations. :)

**Comment by Luis24989** [comment]
Yeah well you could create the mesh as skeletal and static mesh, make the collision for the static mesh as accurate as possible and then in the skeletal mesh physics assets you can get the collision from the static mesh if I remember correctly

**Comment by Luis24989** [comment]
And you can still change some stuff in the physics asset, you can also make a new one for every part.

**Comment by Luis24989** [comment]
I will test out again if the physics assets work well Together for the modular character I have. 
I will let you know

**Comment by Hextionsh0t** [comment]
Thank you! yes all the parts has their physics assets i just need to
combine them, just like the mesh parts. I won't be simulating physics, but
i do need this for accurate collision also while doing animations. Just
wondered if it's possible. Right now my only way to achieve this is to have
many components with child anim bp's. But this is a MP game and i would
prefer it optimized.

**Comment by Luis24989** [comment]
So. I reviewed it and noticed that as you already mentioned a physics assets doesn't get created out of different physics assets.
One option would be to have a physics asset for the Skeleton and assign that after merging the parts together but that is not an option I think. 
I opened a thread in the forums to get some Infos on how that would work and hope to get answers. Since epic said in the docs where I got that code from that I had to update to the coding standard in ue4 now that physics should work.... 
So when I hear something new I will let you know. 

Luis

**Comment by Hextionsh0t** [comment]
Thanks for looking into this :)

**Comment by wanjianqiang** [comment]
> Hey,
> 
> As far as I noticed by now you can create physic assets for the mesh parts and assign them in their meshes.
> After merging the meshes ragdoll worked fine for me.
> The only problem I noticed so far is that cloth simulation stops working after merging together the meshes.
> I hope that answers your question.
> Kind regards
> 
> Luis

Why physic asset of mesh parts don't work when I merge mesh ?

**Comment by Luis24989** [comment]
Sorry my failure I miss wrote it, I wanted to wrote something different, I didn't mean ragdoll. So to cover things of:


Merging physic assets Doesnt work at the moment you would have to assign one that covers all body parts after merging the meshes together.
Cloth simulation doesn't work after merging meshes together at all even with a physics asset assigned. 

I opened a thread on the ue4 forums to get some help on how I would be possible to fix that. 

If I get any Infos on how it would. Work I will update the code and will let you know. 

Later today I will upload a tutorial on how to use the plugin in its current state and get physics working mostly.

Hope that helps you / makes it clearer for you to understand.

Luis
